# Generated by Django 6.1.1 on 2026-09-18 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(help_text="Reporting year, e.g. 2026."),
                ),
                (
                    "week",
                    models.PositiveIntegerField(
                        help_text="Reporting week number within the year (1-53)."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who is reporting for this week.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-week"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("blocked", "Blocked"),
                        ],
                        help_text="Simple status: On Track, At Risk, or Blocked.",
                        max_length=10,
                    ),
                ),
                (
                    "completion",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated completion percentage (0-100).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "completed_work",
                    models.TextField(
                        blank=True, help_text="What was completed this week."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Short notes on the project."
                    ),
                ),
                (
                    "risks",
                    models.TextField(
                        blank=True, help_text="Current risks and blockers."
                    ),
                ),
                (
                    "action_items",
                    models.TextField(
                        blank=True, help_text="Action items / next steps."
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this feedback is about.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="projects.project",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="The weekly report this feedback belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="projects.weeklyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["project__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklyreport",
            constraint=models.UniqueConstraint(
                fields=("user", "year", "week"), name="unique_user_year_week"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectfeedback",
            constraint=models.UniqueConstraint(
                fields=("report", "project"), name="unique_feedback_per_report_project"
            ),
        ),
    ]
