# Generated by Django 6.1.1 on 2026-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_weeklyreport_projectfeedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects the user is involved in.",
                related_name="members",
                to="projects.project",
            ),
        ),
    ]
