# Generated by Django 6.1.1 on 2026-09-18 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_user_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Short, human-readable alert text.", max_length=300
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recipient has acknowledged this.",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project the notification is about.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="projects.project",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user to be alerted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
